# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: 'mysql:8.0.18'
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_USER: fastcheckin
      MYSQL_PASSWORD: fastcheckin
      MYSQL_DATABASE: fastcheckin
    ports:
      - 13306:3306
    volumes:
      - mysql-fastchekin:/var/lib/mysql
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
volumes:
  mysql-fastchekin: